export const dummyParkingData = [
    { 
        userData: {
            id: 1, 
            name: "Estacionamiento Norte", 
            email: "norte@parking.com",
            password: "password123", 
            address: { street: "Mitre", number: 862, city: "Rosario", latitude: -32.94722, longitude: -60.63991 }, 
        }, 
        capacities: { carCapacity: "5", bikeCapacity: "10", motoCapacity: "5" }, 
        prices: { 
            Auto: { fraccion: "40", hora: "120", "medio dia": "500", "dia completo": "800" }, 
            Camioneta: { fraccion: "60", hora: "180", "medio dia": "700", "dia completo": "1000" }, 
            Moto: { fraccion: "20", hora: "80", "medio dia": "300", "dia completo": "500" }, 
            Bicicleta: { fraccion: "10", hora: "40", "medio dia": "100", "dia completo": "200" }, 
        }, 
        schedule: { 
            L: { openTime: "00:00", closeTime: "22:00" }, 
            Ma: { openTime: "07:00", closeTime: "22:00" }, 
            Mi: { openTime: "00:00", closeTime: "22:00" }, 
            J: { openTime: "00:00", closeTime: "22:00" }, 
            V: { openTime: "07:00", closeTime: "22:00" }, 
            S: { openTime: "08:00", closeTime: "20:00" }, 
            D: { openTime: "08:00", closeTime: "14:00" }, 
            F: { openTime: "08:00", closeTime: "14:00" }, 
        },
        features: {
            isCovered: false,
            has24hSecurity: false,
            hasCCTV: false,
            hasValetService: false,
            hasDisabledParking: false,
            hasEVChargers: false,
            hasAutoPayment: false,
            hasCardAccess: false,
            hasCarWash: false,
            hasRestrooms: false,
            hasBreakdownAssistance: false,
            hasFreeWiFi: false,
        }, 
    },
    { 
        userData: {
            id: 2, 
            name: "Estacionamiento Sur", 
            email: "sur@parking.com",
            password: "securepark2024", 
            address: { street: "San Juan", number: 1207, city: "Rosario", latitude: -32.95005, longitude: -60.64077 }, 
        }, 
        capacities: { carCapacity: "0", bikeCapacity: "15", motoCapacity: "8" }, 
        prices: { 
            Auto: { fraccion: "0", hora: "0", "medio dia": "0", "dia completo": "0" }, 
            Camioneta: { fraccion: "0", hora: "0", "medio dia": "0", "dia completo": "0" }, 
            Moto: { fraccion: "25", hora: "90", "medio dia": "350", "dia completo": "600" }, 
            Bicicleta: { fraccion: "15", hora: "50", "medio dia": "150", "dia completo": "300" }, 
        }, 
        schedule: { 
            L: { openTime: "00:00", closeTime: "20:00" }, 
            Ma: { openTime: "06:00", closeTime: "20:00" }, 
            Mi: { openTime: "06:00", closeTime: "20:00" }, 
            J: { openTime: "00:00", closeTime: "20:00" }, 
            V: { openTime: "06:00", closeTime: "20:00" }, 
            S: { openTime: "07:00", closeTime: "19:00" }, 
            D: { openTime: "08:00", closeTime: "14:00" }, 
            F: { openTime: "08:00", closeTime: "14:00" }, 
        },
        features: {
            isCovered: true,
            has24hSecurity: false,
            hasCCTV: true,
            hasValetService: false,
            hasDisabledParking: true,
            hasEVChargers: false,
            hasAutoPayment: true,
            hasCardAccess: false,
            hasCarWash: false,
            hasRestrooms: true,
            hasBreakdownAssistance: false,
            hasFreeWiFi: true,
        }, 
    },
    { 
        userData: {
            id: 3, 
            name: "Estacionamiento Oeste", 
            email: "oeste@parking.com",
            password: "parkwest123", 
            address: { street: "Entre Rios", number: 1159, city: "Rosario", latitude: -32.950579, longitude: -60.642136 }, 
        }, 
        capacities: { carCapacity: "60", bikeCapacity: "0", motoCapacity: "0" }, 
        prices: { 
            Auto: { fraccion: "50", hora: "150", "medio dia": "600", "dia completo": "1000" }, 
            Camioneta: { fraccion: "80", hora: "200", "medio dia": "800", "dia completo": "1200" }, 
            Moto: { fraccion: "0", hora: "0", "medio dia": "0", "dia completo": "0" }, 
            Bicicleta: { fraccion: "0", hora: "0", "medio dia": "0", "dia completo": "0" }, 
        }, 
        schedule: { 
            L: { openTime: "09:00", closeTime: "21:00" }, 
            Ma: { openTime: "09:00", closeTime: "21:00" }, 
            Mi: { openTime: "09:00", closeTime: "21:00" }, 
            J: { openTime: "09:00", closeTime: "21:00" }, 
            V: { openTime: "09:00", closeTime: "21:00" }, 
            S: { openTime: "10:00", closeTime: "18:00" }, 
            D: { openTime: "10:00", closeTime: "16:00" }, 
            F: { openTime: "10:00", closeTime: "16:00" }, 
        },
        features: {
            isCovered: false,
            has24hSecurity: true,
            hasCCTV: false,
            hasValetService: true,
            hasDisabledParking: false,
            hasEVChargers: true,
            hasAutoPayment: false,
            hasCardAccess: true,
            hasCarWash: false,
            hasRestrooms: false,
            hasBreakdownAssistance: true,
            hasFreeWiFi: false,
        }, 
    },
    { 
        userData: {
            id: 4, 
            name: "Estacionamiento Centro", 
            email: "centro@parking.com",
            password: "centralpark2024", 
            address: { street: "Santa Fe", number: 1261, city: "Rosario", latitude: -32.944760, longitude: -60.639841 }, 
        }, 
        capacities: { carCapacity: "45", bikeCapacity: "20", motoCapacity: "10" }, 
        prices: { 
            Auto: { fraccion: "45", hora: "130", "medio dia": "550", "dia completo": "900" }, 
            Camioneta: { fraccion: "65", hora: "190", "medio dia": "750", "dia completo": "1100" }, 
            Moto: { fraccion: "25", hora: "90", "medio dia": "350", "dia completo": "550" }, 
            Bicicleta: { fraccion: "15", hora: "50", "medio dia": "150", "dia completo": "250" }, 
        }, 
        schedule: { 
            L: { openTime: "06:30", closeTime: "23:00" }, 
            Ma: { openTime: "06:30", closeTime: "23:00" }, 
            Mi: { openTime: "06:30", closeTime: "23:00" }, 
            J: { openTime: "06:30", closeTime: "23:00" }, 
            V: { openTime: "06:30", closeTime: "23:00" }, 
            S: { openTime: "07:30", closeTime: "21:00" }, 
            D: { openTime: "09:00", closeTime: "15:00" }, 
            F: { openTime: "09:00", closeTime: "15:00" }, 
        },
        features: {
            isCovered: true,
            has24hSecurity: false,
            hasCCTV: true,
            hasValetService: false,
            hasDisabledParking: true,
            hasEVChargers: false,
            hasAutoPayment: true,
            hasCardAccess: false,
            hasCarWash: true,
            hasRestrooms: true,
            hasBreakdownAssistance: false,
            hasFreeWiFi: true,
        }, 
    },
    { 
        userData: {
            id: 5, 
            name: "Estacionamiento Este", 
            email: "este@parking.com",
            password: "eastparking456", 
            address: { street: "3 de Febrero", number: 1053, city: "Rosario", latitude: -32.952930, longitude: -60.639052 }, 
        }, 
        capacities: { carCapacity: "20", bikeCapacity: "5", motoCapacity: "3" }, 
        prices: { 
            Auto: { fraccion: "35", hora: "100", "medio dia": "450", "dia completo": "700" }, 
            Camioneta: { fraccion: "55", hora: "160", "medio dia": "650", "dia completo": "900" }, 
            Moto: { fraccion: "15", hora: "60", "medio dia": "250", "dia completo": "400" }, 
            Bicicleta: { fraccion: "8", hora: "30", "medio dia": "80", "dia completo": "150" }, 
        }, 
        schedule: { 
            L: { openTime: "08:00", closeTime: "21:30" }, 
            Ma: { openTime: "08:00", closeTime: "21:30" }, 
            Mi: { openTime: "08:00", closeTime: "21:30" }, 
            J: { openTime: "08:00", closeTime: "21:30" }, 
            V: { openTime: "08:00", closeTime: "21:30" }, 
            S: { openTime: "09:00", closeTime: "19:00" }, 
            D: { openTime: "10:00", closeTime: "14:00" }, 
            F: { openTime: "10:00", closeTime: "14:00" }, 
        },
        features: {
            isCovered: false,
            has24hSecurity: true,
            hasCCTV: false,
            hasValetService: false,
            hasDisabledParking: true,
            hasEVChargers: true,
            hasAutoPayment: false,
            hasCardAccess: true,
            hasCarWash: false,
            hasRestrooms: false,
            hasBreakdownAssistance: true,
            hasFreeWiFi: false,
        }, 
    },
    { 
        userData: {
            id: 6, 
            name: "Estacionamiento Parque", 
            email: "parque@parking.com",
            password: "parklife2024", 
            address: { street: "Corrientes", number: 1058, city: "Rosario", latitude: -32.94901, longitude: -60.64321 }, 
        }, 
        capacities: { carCapacity: "75", bikeCapacity: "12", motoCapacity: "0" }, 
        prices: { 
            Auto: { fraccion: "55", hora: "170", "medio dia": "650", "dia completo": "1100" }, 
            Camioneta: { fraccion: "85", hora: "220", "medio dia": "850", "dia completo": "1300" }, 
            Moto: { fraccion: "30", hora: "100", "medio dia": "400", "dia completo": "600" }, 
            Bicicleta: { fraccion: "20", hora: "60", "medio dia": "200", "dia completo": "350" }, 
        }, 
        schedule: { 
            L: { openTime: "00:30", closeTime: "23:30" }, 
            Ma: { openTime: "05:30", closeTime: "23:30" }, 
            Mi: { openTime: "05:30", closeTime: "23:30" }, 
            J: { openTime: "05:30", closeTime: "23:30" }, 
            V: { openTime: "05:30", closeTime: "23:30" }, 
            S: { openTime: "06:30", closeTime: "22:00" }, 
            D: { openTime: "07:00", closeTime: "16:00" }, 
            F: { openTime: "07:00", closeTime: "16:00" }, 
        },
        features: {
            isCovered: true,
            has24hSecurity: true,
            hasCCTV: true,
            hasValetService: false,
            hasDisabledParking: false,
            hasEVChargers: false,
            hasAutoPayment: true,
            hasCardAccess: true,
            hasCarWash: false,
            hasRestrooms: true,
            hasBreakdownAssistance: false,
            hasFreeWiFi: true,
        }, 
    },
    { 
        userData: {
            id: 7, 
            name: "Estacionamiento Universitario", 
            email: "universitario@parking.com",
            password: "campus2024", 
            address: { street: "Cordoba", number: 977, city: "Rosario", latitude: -32.94678, longitude: -60.63654 }, 
        }, 
        capacities: { carCapacity: "50", bikeCapacity: "40", motoCapacity: "12" }, 
        prices: { 
            Auto: { fraccion: "40", hora: "120", "medio dia": "500", "dia completo": "850" }, 
            Camioneta: { fraccion: "70", hora: "190", "medio dia": "750", "dia completo": "1050" }, 
            Moto: { fraccion: "20", hora: "80", "medio dia": "300", "dia completo": "500" }, 
            Bicicleta: { fraccion: "10", hora: "40", "medio dia": "120", "dia completo": "220" }, 
        }, 
        schedule: { 
            L: { openTime: "07:00", closeTime: "22:30" }, 
            Ma: { openTime: "07:00", closeTime: "22:30" }, 
            Mi: { openTime: "07:00", closeTime: "22:30" }, 
            J: { openTime: "07:00", closeTime: "22:30" }, 
            V: { openTime: "07:00", closeTime: "22:30" }, 
            S: { openTime: "08:00", closeTime: "20:00" }, 
            D: { openTime: "09:00", closeTime: "15:00" }, 
            F: { openTime: "09:00", closeTime: "15:00" }, 
        },
        features: {
            isCovered: false,
            has24hSecurity: true,
            hasCCTV: false,
            hasValetService: true,
            hasDisabledParking: true,
            hasEVChargers: false,
            hasAutoPayment: false,
            hasCardAccess: true,
            hasCarWash: true,
            hasRestrooms: false,
            hasBreakdownAssistance: true,
            hasFreeWiFi: false,
        }, 
    },
    { 
        userData: {
            id: 8, 
            name: "Estacionamiento Uteniano", 
            email: "uteniano@parking.com",
            password: "uteniano2024", 
            address: { street: "Zeballos", number: 1477, city: "Rosario", latitude: -32.954131, longitude: -60.645315}, 
        }, 
        capacities: { carCapacity: "40", bikeCapacity: "30", motoCapacity: "7" }, 
        prices: { 
            Auto: { fraccion: "48", hora: "140", "medio dia": "580", "dia completo": "950" }, 
            Camioneta: { fraccion: "75", hora: "210", "medio dia": "780", "dia completo": "1150" }, 
            Moto: { fraccion: "22", hora: "85", "medio dia": "320", "dia completo": "520" }, 
            Bicicleta: { fraccion: "12", hora: "45", "medio dia": "130", "dia completo": "240" }, 
        }, 
        schedule: { 
            L: { openTime: "06:00", closeTime: "22:00" }, 
            Ma: { openTime: "06:00", closeTime: "22:00" }, 
            Mi: { openTime: "06:00", closeTime: "22:00" }, 
            J: { openTime: "06:00", closeTime: "22:00" }, 
            V: { openTime: "06:00", closeTime: "22:00" }, 
            S: { openTime: "07:00", closeTime: "20:00" }, 
            D: { openTime: "08:00", closeTime: "16:00" }, 
            F: { openTime: "08:00", closeTime: "16:00" }, 
        },
        features: {
            isCovered: true,
            has24hSecurity: false,
            hasCCTV: true,
            hasValetService: false,
            hasDisabledParking: false,
            hasEVChargers: true,
            hasAutoPayment: false,
            hasCardAccess: true,
            hasCarWash: false,
            hasRestrooms: true,
            hasBreakdownAssistance: false,
            hasFreeWiFi: true,
        }, 
    }
];