# Generated by Django 5.1.3 on 2024-11-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('is_covered', models.BooleanField()),
                ('entrance', models.CharField(max_length=100)),
                ('exit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_guarded', models.BooleanField()),
                ('has_light_security', models.BooleanField()),
                ('has_gated_access', models.BooleanField()),
                ('has_car_wash', models.BooleanField()),
                ('has_battery_assistance', models.BooleanField()),
                ('has_free_wifi', models.BooleanField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='estacionamientos.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_hours', models.IntegerField()),
                ('is_accessible', models.BooleanField()),
                ('is_easy_pay', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.CharField(max_length=100)),
                ('discounts', models.CharField(blank=True, max_length=200, null=True)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='estacionamientos.parking')),
            ],
        ),
    ]
